#Message sent to console when command cannot be executed by console
console_error_message: '&8[&c*&8] &cYou are unable to execute this command!' 

#No Permission Message
no_perm_message: &cYou do not have permission to execute this command

#FlyCommand Below
FlyCommand:
  flying_enabled:' &8[&6&lYou &6&lHave &6&lEnabled &e&lFlying&b&l!&8]'
  flying_disabled:' &8[&6&lYou &6&lHave &c&lDisabled &b&lFlying&b&l!&8]'